# Generated by Django 2.1.3 on 2018-11-07 17:28

from django.db import migrations, models
import frontend.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='School Name')),
                ('url', models.CharField(max_length=100, verbose_name='School website url')),
                ('fulltime', models.BooleanField(blank=True, verbose_name='Fulltime available?')),
                ('hardware', models.BooleanField(blank=True, verbose_name='Hardware included?')),
                ('has_online', models.BooleanField(blank=True, verbose_name='Online Offered?')),
                ('only_online', models.BooleanField(blank=True, verbose_name='Online only?')),
                ('accredited', models.BooleanField(blank=True, verbose_name='VA Accredited?')),
                ('housing', models.BooleanField(blank=True, verbose_name='Housing Included?')),
                ('mooc', models.BooleanField(blank=True, verbose_name='MOOC Only?')),
                ('rep_name', models.CharField(max_length=100, verbose_name='School Representative')),
                ('rep_email', models.CharField(max_length=100, verbose_name='Representative Email')),
                ('address1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Zipcode')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('logo', models.ImageField(upload_to='logos/', validators=[frontend.forms.image_validator], verbose_name='Logo')),
            ],
        ),
    ]
