# Generated by Django 2.1.3 on 2018-11-07 19:22

from django.db import migrations, models
import frontend.forms


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeschool',
            name='logo',
            field=models.ImageField(upload_to='logos', validators=[frontend.forms.image_validator], verbose_name='Logo'),
        ),
    ]
